import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import type { GeneratedFile, Plan } from "@shared/schemas";
import type { Generation, Project } from "../db/schema";
import { slugify } from "../lib/random";
import { RUNTIME_SOURCE_DIR } from "../sandbox/runtimeAssets";

const require = createRequire(import.meta.url);

/** Pin the exported project to the exact versions SayShip itself runs (fallbacks if absent). */
function installedVersion(pkg: string, fallback: string): string {
  try {
    return (require(`${pkg}/package.json`) as { version: string }).version;
  } catch {
    return fallback;
  }
}

const INDEX_HTML = (title: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title.replace(/</g, "&lt;")}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

const VITE_CONFIG = `import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    // Generated code imports its data layer from "sayship"; locally that's src/sayship.js.
    alias: { sayship: fileURLToPath(new URL("./src/sayship.js", import.meta.url)) },
  },
});
`;

const MAIN_JSX = `import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "./index.css";

createRoot(document.getElementById("root")).render(<App />);
`;

function readme(project: Project, plan: Plan, gen: Generation): string {
  return `# ${plan.appName}

${plan.description}

Generated by **SayShip** (version ${gen.version}) from the prompt:

> ${project.prompt.replace(/\n/g, "\n> ")}

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

## Features

${plan.features.map((f) => `- ${f}`).join("\n") || "- See src/App.jsx"}

## Data

SayShip apps read and write data with \`useCollection()\` from \`"sayship"\`.
In SayShip that's a hosted Postgres-backed API; in this export, \`src/sayship.js\` implements
the same API on top of \`localStorage\`, so the app runs anywhere without a backend.
Replace it with calls to your own API to share data between users.

## Files

${plan.files.map((f) => `- \`src/${f.path}\`: ${f.purpose}`).join("\n")}
`;
}

/**
 * A runnable Vite + React + Tailwind project containing the generated files unchanged: they
 * are real ES modules, so the same code that ran in the preview runs here.
 */
export function buildViteProject(project: Project, gen: Generation): GeneratedFile[] {
  const plan: Plan = project.plan ?? {
    appName: project.name,
    description: project.prompt,
    entities: [],
    features: [],
    files: gen.files.map((f) => ({ path: f.path, purpose: "Generated file" })),
  };
  const name = slugify(plan.appName);
  const react = installedVersion("react", "19.3.0");

  const pkg = {
    name,
    private: true,
    version: "0.1.0",
    type: "module",
    scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
    dependencies: { react: `^${react}`, "react-dom": `^${react}` },
    devDependencies: {
      vite: `^${installedVersion("vite", "8.3.0")}`,
      "@vitejs/plugin-react": `^${installedVersion("@vitejs/plugin-react", "6.1.1")}`,
      tailwindcss: `^${installedVersion("tailwindcss", "4.3.3")}`,
      "@tailwindcss/vite": `^${installedVersion("@tailwindcss/vite", "4.3.3")}`,
    },
  };

  const manifest = {
    generator: "SayShip",
    prompt: project.prompt,
    version: gen.version,
    model: gen.model,
    generatedAt: gen.createdAt.toISOString(),
    plan,
  };

  return [
    { path: "package.json", content: JSON.stringify(pkg, null, 2) + "\n" },
    { path: "index.html", content: INDEX_HTML(plan.appName) },
    { path: "vite.config.js", content: VITE_CONFIG },
    { path: ".gitignore", content: "node_modules\ndist\n" },
    { path: "README.md", content: readme(project, plan, gen) },
    { path: "sayship.json", content: JSON.stringify(manifest, null, 2) + "\n" },
    { path: "src/main.jsx", content: MAIN_JSX },
    { path: "src/index.css", content: '@import "tailwindcss";\n' },
    { path: "src/sayship.js", content: readFileSync(path.join(RUNTIME_SOURCE_DIR, "sdk-local.js"), "utf8") },
    ...gen.files.map((f) => ({ path: `src/${f.path}`, content: f.content })),
  ];
}
