import { eq } from "drizzle-orm";
import { Router, type Request } from "express";
import { z } from "zod";
import type { AppDeps } from "../app";
import { decryptSecret } from "../auth/crypto";
import { currentUser, requireAuth } from "../auth/middleware";
import { isUniqueViolation } from "../db/errors";
import { projects, users, type Generation, type Project } from "../db/schema";
import { GitHubError, pushToGitHub } from "../export/github";
import { buildViteProject } from "../export/viteProject";
import { zipProject } from "../export/zip";
import { HttpError } from "../lib/http";
import { randomId, slugify } from "../lib/random";
import { bundleGeneration } from "../sandbox/bundle";
import { getGeneration, getLatestGeneration, getOwnedProject } from "../services/projects";
import { parseId } from "./projects";

const requestOrigin = (req: Request) => `${req.protocol}://${req.host}`;

const VersionBody = z.object({ version: z.number().int().positive().optional() });
const GitHubBody = VersionBody.extend({
  repoName: z
    .string()
    .trim()
    .regex(/^[A-Za-z0-9._-]{1,100}$/, "Repository names use letters, digits, '.', '_' or '-'"),
});

/** Publishing, ZIP export and GitHub push: the ways a generated app leaves the workspace. */
export function shipRouter({ db, env }: AppDeps) {
  const router = Router();
  router.use(requireAuth);

  async function pickVersion(project: Project, version: number | undefined): Promise<Generation> {
    const gen = version ? await getGeneration(db, project.id, version) : await getLatestGeneration(db, project.id);
    if (!gen) throw new HttpError(409, "nothing_to_ship", "Generate the app first.");
    return gen;
  }

  /** One click: the version goes live at /p/:slug (the slug stays stable across re-publishes). */
  router.post("/:id/publish", async (req, res) => {
    const project = await getOwnedProject(db, currentUser(req).id, parseId(req.params.id));
    const gen = await pickVersion(project, VersionBody.parse(req.body ?? {}).version);
    const built = await bundleGeneration(gen, "live");
    if (!built.ok) throw new HttpError(422, "build_failed", `v${gen.version} doesn't build. Fix it before publishing.`);

    for (let attempt = 0; ; attempt++) {
      const slug = project.publishedSlug ?? `${slugify(project.plan?.appName ?? project.name, 32)}-${randomId(6)}`;
      try {
        await db
          .update(projects)
          .set({ publishedSlug: slug, publishedVersion: gen.version })
          .where(eq(projects.id, project.id));
        res.json({ slug, version: gen.version, url: `${requestOrigin(req)}/p/${slug}` });
        return;
      } catch (err) {
        if (attempt < 3 && isUniqueViolation(err)) continue; // random slug collided; draw again
        throw err;
      }
    }
  });

  router.delete("/:id/publish", async (req, res) => {
    const project = await getOwnedProject(db, currentUser(req).id, parseId(req.params.id));
    await db.update(projects).set({ publishedVersion: null }).where(eq(projects.id, project.id));
    res.status(204).end();
  });

  /** A runnable Vite project, zipped. */
  router.get("/:id/versions/:version/export.zip", async (req, res) => {
    const project = await getOwnedProject(db, currentUser(req).id, parseId(req.params.id));
    const gen = await getGeneration(db, project.id, parseId(req.params.version, "Version"));
    const folder = slugify(project.plan?.appName ?? project.name);
    const zip = zipProject(folder, buildViteProject(project, gen));
    res
      .set({
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${folder}-v${gen.version}.zip"`,
        "Cache-Control": "no-store",
      })
      .send(zip);
  });

  /** Creates a GitHub repo with the Vite project in one commit. Requires a connected GitHub account. */
  router.post("/:id/export/github", async (req, res) => {
    const user = currentUser(req);
    const project = await getOwnedProject(db, user.id, parseId(req.params.id));
    const body = GitHubBody.parse(req.body);
    const gen = await pickVersion(project, body.version);

    const [row] = await db.select({ tokenEnc: users.githubTokenEnc }).from(users).where(eq(users.id, user.id));
    if (!row?.tokenEnc) throw new HttpError(409, "github_not_connected", "Connect your GitHub account first.");
    const token = decryptSecret(row.tokenEnc, env.SESSION_SECRET);

    try {
      const result = await pushToGitHub(token, {
        repoName: body.repoName,
        description: project.plan?.description ?? project.prompt,
        files: buildViteProject(project, gen),
        message: `${project.plan?.appName ?? project.name} v${gen.version}, generated by PromptShip`,
      });
      res.status(201).json(result);
    } catch (err) {
      if (err instanceof GitHubError) {
        if (err.status === 401) {
          await db.update(users).set({ githubTokenEnc: null, githubLogin: null }).where(eq(users.id, user.id));
          throw new HttpError(409, "github_not_connected", "GitHub access has expired. Connect GitHub again.");
        }
        throw new HttpError(502, "github_error", `GitHub: ${err.message}`);
      }
      throw err;
    }
  });

  return router;
}
